[project]
name = "mylox"
version = "0.1.0"
description = "intérprete de lox TP Lenguajes y Compiladores"
requires-python = ">=3.12"

[project.scripts]
mylox = "mylox.cli:main"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
